---
title: "ETF Portfolio Simulation Dashboard"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Hướng Dẫn", href: "https://vohoanghac.com", align: left }
    source_code: "https://github.com/vhoanghac/ETF_Portfolio_Simulation"
    theme:
      version: 4
      bootswatch: minty
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(shinyjs)

# Core
library(tidyverse)
library(tidyquant)
library(timetk)
library(data.table)
library(tidytable)
library(scales)

# Interactive Visualizations
library(plotly)

# Load data
library(fst)
```

```{r}
# Load data
data <- read.fst("data/tidied/full_data.fst") %>% 
  tidytable::mutate(date   = as_date(date),
                    symbol = toupper(symbol))
```


Sidebar {.sidebar}
--------------------

### Danh mục:

```{r}
useShinyjs(rmd = TRUE)

# Input để chọn ETF 1
div(style = "display: flex;",
    
    pickerInput(
      inputId  = "picker_etf1",
      label    = "ETF 1:",
      choices  = unique(data$symbol),
      selected = "VN30",
      multiple = FALSE),
    
    numericInput(
      inputId = "weight_etf1",
      label   = "Tỷ trọng:",
      value   = 0.5,
      min     = 0,
      max     = 1,
      step    = 0.05)
    )
    
# Input để chọn ETF 2
div(style = "display: flex;",
    
    pickerInput(
      inputId  = "picker_etf2",
      label    = "ETF 2:",
      choices  = unique(data$symbol),
      selected = "MIDCAP",
      multiple = FALSE),
    
    numericInput(
      inputId = "weight_etf2",
      label   = "Tỷ trọng:",
      value   = 0.5,
      min     = 0,
      max     = 1,
      step    = 0.05
      )
    )

# Input Rebalance
awesomeRadio(
  inputId  = "rebalance_on",
  label    = "Tái cân bằng:",
  choices  = "Hằng năm",
  selected = "Hằng năm",
  inline   = TRUE,
  status   = "success"
)

```

### So sánh với

```{r}
# picker_etf de so sanh voi cac quy ETF khac

pickerInput(
  inputId  = "picker_etf",
  label    = h4("Các ETF:"),
  choices  = unique(data$symbol),
  selected = "VN30",
  multiple = TRUE,
  options  = list(`actions-box`          = TRUE,
                  size                   = 10,
                  `selected-text-format` = "ETF")
)
```


```{r}
# Apply Button:
actionButton(inputId = "simulate", 
             label   = "Apply", 
             icon    = icon("play"))

# Reset Button:
actionButton(inputId = "reset_simulate", 
             label   = "Reset",
             icon    = icon("sync"))

# Sau khi bấm nút reset thì trả về so sánh với ETF VN30
observeEvent(eventExpr = input$reset_simulate, handlerExpr = {
  
  updatePickerInput(
    session  = session,
    inputId  = "picker_etf",
    selected = "VN30")
  
  # Delay
  delay(ms = 150, expr = {
    click(id = "simulate")
  })
  
})
```

```{r}
# MAIN event Reactive
# Mọi dữ liệu trên dashboard đều tính toán từ data_tbl()
# Sau khi click nút Apply thì lọc data theo tên của Input picker_etf

data_tbl <- eventReactive(

  eventExpr = input$simulate,

  valueExpr = {

    # 1. Thiết lập tỷ trọng ETF
    # Set thẳng tỷ trọng dựa theo symbol
    # Symbol:  input$picker_etf1 + input$picker_etf2
    # Weights: input$weight_etf1 + input$weight_etf2
    weights_df <- tibble(symbol  = c(input$picker_etf1, input$picker_etf2),
                         weights = c(input$weight_etf1, input$weight_etf2))
    
    # 2. Thiết lập danh mục
    portfolio <- data %>%
      
      # Filter dựa theo symbol
      # Symbol: input$picker_etf1 + input$picker_etf2
      tidytable::filter(symbol %in% c(input$picker_etf1, input$picker_etf2)) %>% 
      
      # Tính toán danh mục
      tq_portfolio(assets_col   = symbol,
                   returns_col  = returns,
                   weights      = weights_df,
                   col_rename   = "returns",
                   rebalance_on = "years") %>%   
      
      tidytable::mutate(symbol = "PORTFOLIO") 
    
    
    # 3. Gộp dữ liệu để so sánh portfolio với ETF
    # Symbol so sánh: input$picker_etf 
    data_combined <- portfolio %>% 
      bind_rows(data %>% 
                  tidytable::filter(symbol %in% c(input$picker_etf)))
    

    return(data_combined)

    },

  ignoreNULL = FALSE

  )

```

Row
-----------------------------------------------------------------------

### Lợi nhuận bình quân/năm (PORTFOLIO)

```{r}
# Lấy giá trị lợi nhuận
ann_ret <- reactive({
  
  data_tbl() %>% 
    tidytable::filter(symbol == "PORTFOLIO") %>% 
    tq_performance(Ra              = returns,
                   Rb              = NULL,
                   performance_fun = Return.annualized) %>% 
    pull(AnnualizedReturn) %>% 
    scales::percent(accuracy = 0.1)

})

# Render ValueBox dựa vào giá trị lợi nhuận đã tính ở trên
renderValueBox({
  valueBox(ann_ret(), icon="fa-solid fa-percent", color = "success")
})

```

### Mức sụt giảm lớn nhất (PORTFOLIO)

```{r}
max_dd <- reactive({
  
  data_tbl() %>% 
    tidytable::filter(symbol == "PORTFOLIO") %>% 
    tq_performance(Ra              = returns,
                   Rb              = NULL,
                   performance_fun = maxDrawdown) %>% 
    pull(maxDrawdown.1) %>% 
    scales::percent(accuracy = 0.1)
  
})

renderValueBox({
  valueBox(max_dd(), icon="fa-solid fa-arrow-trend-down", color = "warning")
})

```


Row
--------------------

### Lợi nhuận tích lũy
    
```{r}
# Chuẩn bị dữ liệu:
cum_ret <- reactive({

  data_tbl() %>%
    tidytable::mutate(growth    = cumprod(1 + returns), .by = symbol) %>%
    tidytable::mutate(date_txt  = format(date, "%d-%m-%Y"),
                      label_txt = str_glue("Ngày: {date_txt}
                                           ETF: {symbol}
                                           Lợi nhuận tích lũy: {scales::percent(growth - 1, accuracy = 0.1)}"))
})

# Output:
output$plotly_cum_ret <- renderPlotly({
  
  p1 <- cum_ret() %>%

    ggplot(aes(x     = date,
               y     = growth,
               color = symbol)) + theme_tq() +

    geom_line(linewidth = 0.5) +
    geom_line(aes(text  = label_txt)) +

    expand_limits(y = 0.5) +
    scale_x_date(breaks = scales::pretty_breaks(n = 10)) +

    geom_hline(yintercept = 1,
               linetype   = "dashed",
               color      = "#7A7574") +

    labs(x = "",
         y = "")
  
  ggplotly(p1, tooltip = "text")
  
  })

# Plot
plotlyOutput(outputId = "plotly_cum_ret")
```

Row
--------------------

### Hiệu suất theo năm

```{r}
yearly_ret <- reactive({
  data_tbl() %>% 
    tidytable::mutate(year     = floor(year(date))) %>% 
    tidytable::mutate(year_ret = cumprod(1 + returns) - 1,
                      .by      = c(year, symbol)) %>% 
    
    # Để dễ dàng cho việc chọn dữ liệu, đặt tên "ret_" trước mỗi column
    pivot_wider(names_from     = symbol,
                values_from    = year_ret, date,
                names_prefix   = "ret_") %>% 
    
    tidytable::mutate(year = as.factor(floor(year(date)))) %>% 
    
    # Bằng cách này có thể chọn nhiều column khi user lựa chọn nhiều quỹ
    tidytable::summarise(across(starts_with("ret_"), ~last(.)),
                         .by = year) %>% 
    # Sau khi chọn xong thì xóa prefix
    rename_all(~str_remove(., "^ret_")) %>% 
    
    tidytable::filter(year != "2023") %>% 
    pivot_longer(names_to   = "symbol",
                 values_to  = "returns", !year) 
  
})

#Output

output$plotly_yearly_ret <- renderPlotly({


  p2 <- yearly_ret() %>%
    ggplot(aes(x = year, 
               y = returns, 
               fill = symbol)) + theme_tq() + 
    
    geom_bar(stat = "identity", position = "dodge",
             aes(text = paste("Năm: ", year,
                              "<br>", "ETF: ", symbol,
                              "<br>", "Hiệu suất: ", round(returns * 100, 2), "%")),
             hoverinfo = "text") +
    expand_limits(y = 0.5) +
    scale_y_continuous(labels = scales::percent_format()) +
    
    labs(x = "",
         y = "")
  
  ggplotly(p2, tooltip = "text")

})


# Plot
plotlyOutput(outputId = "plotly_yearly_ret")

```

Row
--------------------

### Lợi nhuận quy năm theo chu kỳ nắm giữ

```{r}
# Quãng thời gian tính rolling annualized returns

radioGroupButtons(
  inputId   = "time_period",
  label     = "Chu kỳ nắm giữ (Tháng)",
  choices   = c(6, 12, 24, 36, 48),
  selected  = 12,
  status    = "primary",
  justified = TRUE,
  checkIcon = list(
    yes = icon("ok", lib = "glyphicon"))
)
```

```{r}

# Tính rolling annualized returns:

rolling_returns_tbl <- reactive({
  
  time_period <- as.integer(input$time_period)
  
  # Tính rolling returns
  data_tbl() %>% 
    dplyr::group_by(symbol) %>% 
    
    # Vì dữ liệu theo ngày nên
    # Tính trung bình có 21 ngày giao dịch trong tháng
    # Mỗi năm có 252 ngày
    tk_augment_slidify(.value = returns,
                     .period  = time_period * 21,
                     .f       = Return.annualized,
                     scale    = 252,
                     .names   = "roll_annr",
                     .align   = "right") %>% 
    
    dplyr::mutate(date_2 = lag(date, n = time_period * 21)) %>% 
    dplyr::ungroup() %>% 
    tidytable::mutate(date_txt   = format(date, "%d-%m-%Y"),
                      date_2_txt = format(date_2, "%d-%m-%Y"),
                      label_txt  = str_glue("Ngày mua: {date_2_txt}
                                            Giá trị tại: {date_txt}
                                            ETF: {symbol}
                                            Lợi nhuận mỗi năm: {scales::percent(roll_annr, accuracy = 0.1)}"))
})

# Output:
output$plotly_rolling_returns <- renderPlotly({
  
  p3 <- rolling_returns_tbl() %>% 
    ggplot(aes(x     = date,
               y     = roll_annr,
               color = symbol)) + theme_tq() + 
    
    geom_line(size = 0.5) + 
    geom_line(aes(text = label_txt)) +
    
    geom_hline(yintercept = 0, 
               linetype   = "dashed", 
               color      = "#7A7574") +
    
    scale_y_continuous(labels = scales::percent_format()) +
    
    scale_x_date(breaks = scales::pretty_breaks(n = 10)) +
    
    labs(x = "",
         y = "")
  
  ggplotly(p3, tooltip = "text") %>% 
    layout(margin = list(b = 120)) 
  
})

# Plot
plotlyOutput(outputId = "plotly_rolling_returns")
```


Row
--------------------

### Tỷ lệ sụt giảm so với đỉnh

```{r}
# Tính drawdown
drawdown <- reactive({

  data_tbl() %>%
    tidytable::mutate(growth    = cumprod(1 + returns) - 1,
                      maxgrowth = cummax(growth + 1),
                      drawdown  = (growth + 1) / maxgrowth - 1,
                      .by       = symbol) %>% 
    tidytable::mutate(label_txt = str_glue("Mức sụt giảm: {scales::percent(drawdown, accuracy = 0.1)}"))
})

# Output

output$plotly_drawdown <- renderPlotly({
  
  p4 <- drawdown() %>% 
    ggplot(aes(x     = date,
               y     = drawdown,
               color = symbol)) + theme_tq() + 
    
    geom_line(linewidth = 0.5) + 
    
    geom_point(aes(text = label_txt), size = 0.1) +
    
    geom_hline(yintercept = 0, 
               linetype   = "dashed", 
               color      = "#7A7574") +
    
    facet_wrap(~symbol, ncol = 2) +
    
    scale_y_continuous(labels = scales::percent_format()) +
    scale_x_date(breaks = scales::pretty_breaks(n = 10)) +
    
    labs(x = "",
         y = "")
  
  ggplotly(p4, tooltip = "text")
  
})

# Plot
plotlyOutput(outputId = "plotly_drawdown")
```